<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

  <title>Makefile - The Go Programming Language</title>

<link type="text/css" rel="stylesheet" href="/lib/godoc/style.css">

<script type="text/javascript">window.initFuncs = [];</script>
</head>
<body>

<div id="topbar" class="wide"><div class="container">

<form method="GET" action="/search">
<div id="menu">
<a href="/doc/">Documents</a>
<a href="/pkg/">Packages</a>
<a href="/project/">The Project</a>
<a href="/help/">Help</a>
<a href="/blog/">Blog</a>

<input type="text" id="search" name="q" class="inactive" value="Search" placeholder="Search">
</div>
<div id="heading"><a href="/">The Go Programming Language</a></div>
</form>

</div></div>



<div id="page" class="wide">
<div class="container">


  <div id="plusone"><g:plusone size="small" annotation="none"></g:plusone></div>
  <h1>Text file Makefile</h1>




<div id="nav"></div>


<pre><span id="L1" class="ln">     1</span>	build:
<span id="L2" class="ln">     2</span>		script/build.sh
<span id="L3" class="ln">     3</span>	start:
<span id="L4" class="ln">     4</span>		script/start.sh
<span id="L5" class="ln">     5</span>	stop:
<span id="L6" class="ln">     6</span>		script/stop.sh
<span id="L7" class="ln">     7</span>	clean: stop
<span id="L8" class="ln">     8</span>		rm -rf bin
<span id="L9" class="ln">     9</span>		rm -rf pkg
<span id="L10" class="ln">    10</span>		rm -rf ~/.config/emp/log/*
<span id="L11" class="ln">    11</span>	
<span id="L12" class="ln">    12</span>	clobber: clean
<span id="L13" class="ln">    13</span>		rm -rf src/github.com
<span id="L14" class="ln">    14</span>		rm -rf src/code.google.com
</pre><p><a href="/Makefile?m=text">View as plain text</a></p>

<div id="footer">
Build version go1.2.<br>
Except as <a href="http://code.google.com/policies.html#restrictions">noted</a>,
the content of this page is licensed under the
Creative Commons Attribution 3.0 License,
and code is licensed under a <a href="/LICENSE">BSD license</a>.<br>
<a href="/doc/tos.html">Terms of Service</a> | 
<a href="http://www.google.com/intl/en/policies/privacy/">Privacy Policy</a>
</div>

</div><!-- .container -->
</div><!-- #page -->

<script type="text/javascript" src="/lib/godoc/jquery.js"></script>

<script type="text/javascript" src="/lib/godoc/godocs.js"></script>

</body>
</html>

